cq_0_tests:
  sparql_template: 'cq_templates/cq0.sparql'
  parameters:
    cq_0_parameter_1: 'Amlodipine'
  expected_output: 'cq_expected_results/cq_0_expected_results.json'
cq_1_tests:
  sparql_template: 'cq_templates/cq1.sparql'
  parameters:
    cq_1_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/cq_1_expected_results.json'
cq_2_tests:
  sparql_template: 'cq_templates/cq2.sparql'
  parameters:
    cq_2_parameter_1: 'amlodipine mesylate monohydrate'
  expected_output: 'cq_expected_results/cq_2_expected_results.json'
cq_3-1a_tests:
  sparql_template: 'cq_templates/cq3-1a.sparql'
  parameters:
    cq_3-1a_parameter_1: 'amlodipine mesylate monohydrate'
  expected_output: 'cq_expected_results/cq_3-1a_expected_results.json'
cq_3-1b_tests:
  sparql_template: 'cq_templates/cq3-1b.sparql'
  parameters:
    cq_3-1b_parameter_1: 'amlodipine mesylate monohydrate'
  expected_output: 'cq_expected_results/cq_3-1b_expected_results.json'
cq_3a_tests:
  sparql_template: 'cq_templates/cq3a.sparql'
  parameters:
    cq_3a_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/cq_3a_expected_results.json'
cq_3b_tests:
  sparql_template: 'cq_templates/cq3b.sparql'
  parameters:
    cq_3b_parameter_1: 'amlodipine'
    cq_3b_parameter_2: 'terlipressin'
  expected_output: 'cq_expected_results/cq_3b_expected_results.json'
cq_4-1_tests:
  sparql_template: 'cq_templates/cq4-1.sparql'
  parameters:
    cq_4-1_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/cq_4-1_expected_results.json'
cq_4_tests:
  sparql_template: 'cq_templates/cq4.sparql'
  parameters:
    cq_4_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/cq_4_expected_results.json'
cq_5_tests:
  sparql_template: 'cq_templates/cq5.sparql'
  parameters:
    cq_5_parameter_1: 'Norvasc medicinal product'
  expected_output: 'cq_expected_results/cq_5_expected_results.json'
cq_6_tests:
  sparql_template: 'cq_templates/cq6.sparql'
  parameters:
    cq_6_parameter_1: 'amlodipine besylate'
    cq_6_parameter_2: 'amlodipine'
  expected_output: 'cq_expected_results/cq_6_expected_results.json'
cq_7_tests:
  sparql_template: 'cq_templates/cq7.sparql'
  parameters:
    cq_7_parameter_1: 'terlipressin acetate'
  expected_output: 'cq_expected_results/cq_7_expected_results.json'
cq_8_tests:
  sparql_template: 'cq_templates/cq8.sparql'
  parameters:
    cq_8_parameter_1: 'Norvasc medicinal product'
  expected_output: 'cq_expected_results/cq_8_expected_results.json'
