cq_0_tests:
  sparql_template: 'cq_templates/cq0.sparql'
  parameters:
    cq_0_parameter_1: 'Amlodipine'
  expected_output: 'cq_expected_results/cq_0_expected_results.json'
cq_1_tests:
  sparql_template: 'cq_templates/cq1.sparql'
  parameters:
    cq_1_parameter_1: 'amlodipine'
  expected_output: 'cq_expected_results/cq_1_expected_results.json'
